name: CI

on: [ push, pull_request ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  ci:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.1', '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Show PHP version
        run: php -v

      - name: Show composer version
        run: composer --version

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer Install dependencies
        run: composer install --no-progress --no-interaction

      - name: PHP CGL
        run: composer cgl
        env:
          COMPOSER_PROCESS_TIMEOUT: 1200

      - name: PHPStan
        run: composer phpstan
        env:
          COMPOSER_PROCESS_TIMEOUT: 1200

      - name: Tests
        run: composer tests
        env:
          COMPOSER_PROCESS_TIMEOUT: 1200
